services:
  - type: web
    name: creditpulse-api
    runtime: python
    region: frankfurt
    plan: free
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PRIVATE_KEY
        sync: false
      - key: CORS_ORIGINS
        sync: false
      - key: CONTRACT_ADDRESS
        value: "0x5BEC88F55ECA9038A9f03E77052314EfDC293Da5"
      - key: RPC_URL
        value: "https://rpc.cc3-testnet.creditcoin.network"
      - key: PYTHON_VERSION
        value: "3.11.0"
